type: app
description: Java Api com OpenAPI e Swagger UI
# template used to create the project
template: hands-on-java-stack/base-template
# list of plugins to be applied after project creation
plugins:
  - plugin: hands-on-java-stack/java-spring-openapi-plugin